### ISSUE TITLE
Adding Google Play Services

### ISSUE THREAD

**Issue by keithweaver** [etenoch/GoldenWords-Android#1]
Hi Enoch,

One thing I just noticed in your build.gradle file was that you have a redundancy. You import:

```
compile 'com.google.android.gms:play-services:7.5.0'
```

then do:

```
compile 'com.google.android.gms:play-services-maps:7.5.0'
```

I believe (I could be wrong) that maps is included in the first line. Also I have had issues with importing all google play services because I dont use most of it (run out of room later on). I recommend changing it to be:

```
compile 'com.google.android.gms:play-services-maps:7.5.0'
compile 'com.google.android.gms:play-services-location:7.5.0'
```

**Comment by etenoch** [comment]
Oh yes, your right. I put the general one in originally for testing and intended to use the only the maps one. Guess i forgot to take out the general one. Also, now that I'm looking at my build.gradle again I've realized theres some other stuff I could take out as well.
Thanks for letting me know

**Comment by keithweaver** [comment]
No problem. App looks great! I'm excited to give it a try.
